name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.19
          pkg: cmd/gptest
          dest: build
          prefix: gptest
          targets: windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          ldflags: -s -w
          buildmode: default
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/gptest-*
