name: goreleaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build
        run: |
          make build_linux
          make build_windows
          make build_macos
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            gptest_linux
            gptest_windows.exe
            gptest_macos
